version: "3.8"

services:
  backend:
    build: ./backend
    image: rodrigoesteves45/flowbiz-backend:latest
    container_name: FlowBiz-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:4000 
    image: rodrigoesteves45/flowbiz-frontend:latest
    container_name: FlowBiz-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
